### ISSUE TITLE
Wrap Tooltip component with Portal

### ISSUE THREAD

**Issue by its-monotype** [hrbengtsen/styple#10]
The fact that the Tooltip component does not use Portal, can lead to issues, for example, when we use it inside the Dialog component:
![image](https://user-images.githubusercontent.com/79363260/213287634-cfc28450-bc7e-4c20-8cc3-aa368420b1fa.png)

**Comment by its-monotype** [comment]
Oops, I didn't notice that you have a very old version of the Radix UI tooltip.

**Comment by hrbengtsen** [comment]
Yeah sorry about that, but thanks for letting me know!

I'm currently trying to get everything updated and rewrite some stuff for a 1.0.

**Comment by its-monotype** [comment]
@hrbengtsen It would be nice, the library is really cool
